# Generated by Django 5.1.1 on 2024-10-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_genre_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
