# Generated by Django 5.1.1 on 2024-10-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_delete_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=333, null=True, unique=True),
        ),
    ]
